import { z } from "zod";

import type { MockCurrentSelfDraft } from "@/lib/mock-current-self-generator";
import { checkInThemeNameSchema, tentativeTextSchema } from "@/lib/ai/schemas/shared";

// Current Self draws from the full theme vocabulary (positive + difficult) —
// unlike most other generators, it must be able to name struggle, tension,
// or contradiction as a theme, not just growth-oriented ones.
export const currentSelfThemesSchema = z.array(checkInThemeNameSchema).min(4).max(6);

// What You Value: exactly the 3 deepest tradeoffs-turned-values that
// repeatedly explain this person's decisions — derived from repeated
// tradeoffs ("what repeatedly wins"), not from theme tags, and not a
// running list of every theme that appeared. Each item is
// "Value name\nEvidence paragraph" — the name is the recognizable label,
// the second line is a short paragraph naming the tradeoff and the pattern
// across multiple unrelated decisions.
export const currentSelfValuesSchema = z.array(tentativeTextSchema).length(3);

// What You Fear Becoming: at most 3 feared future identities, each the
// sibling of a value — a three-part portrait encoded as
// "Theme\nIdentity statement\nSupporting paragraph" (the same newline
// convention the values field uses, with three lines instead of two).
// Derived from actual repeated avoidance patterns in the evidence — never
// generated by negating a value, so it is not positionally tied to the
// values list. Only as many as are clearly supported; never padded.
export const currentSelfAfraidOfBecomingSchema = z.array(tentativeTextSchema).min(1).max(3);

// Your Biggest Tension: the single most important recurring internal
// contradiction, grounded in the actual pattern of decisions recorded.
export const currentSelfCoreTensionSchema = tentativeTextSchema;

// The Tradeoff You Live With: the single recurring cost of this identity,
// encoded as "Strength\nTradeoff\nObservation". Nullish because the section is
// omitted entirely when the evidence is too weak to name a genuine tradeoff —
// the model returns null (or drops the key) rather than inventing one.
export const currentSelfCoreTradeoffSchema = tentativeTextSchema.nullish();

// What's Changing: up to 3 full sentences describing how the identity is evolving.
export const currentSelfRecentGrowthSchema = z.array(tentativeTextSchema).min(1).max(3);

export const currentSelfOutputSchema = z.object({
  title: tentativeTextSchema,
  summary: tentativeTextSchema,
  themes: currentSelfThemesSchema,
  values: currentSelfValuesSchema,
  afraid_of_becoming: currentSelfAfraidOfBecomingSchema,
  core_tension: currentSelfCoreTensionSchema,
  core_tradeoff: currentSelfCoreTradeoffSchema,
  recent_growth: currentSelfRecentGrowthSchema,
}) satisfies z.ZodType<MockCurrentSelfDraft>;

export const currentSelfNullableOutputSchema =
  currentSelfOutputSchema.nullable();

export function parseCurrentSelfOutput(data: unknown): MockCurrentSelfDraft | null {
  if (data === null) {
    return null;
  }

  return currentSelfOutputSchema.parse(data);
}
