export const CONTEXT_LIMITS = {
  TEXT: {
    momentTitle: 200,
    momentDescription: 500,
    pathDescription: 400,
    reflection: 500,
    identityImpact: 400,
    realitySummary: 400,
    crossroadWhatHappened: 400,
    crossroadWhyChosen: 300,
    crossroadLifeStage: 120,
    headline: 200,
    summary: 800,
    question: 400,
    promptContext: 400,
    response: 500,
    contradictionTitle: 200,
    pole: 400,
    alternateSelfName: 120,
    alternateSelfSection: 600,
    evidenceLabel: 200,
    genericLabel: 200,
  },
  COUNTS: {
    moments: 10,
    chosenPaths: 10,
    checkIns: 10,
    identityUpdates: 5,
    futureSelves: 5,
    contradictions: 3,
    alternateSelves: 5,
    answeredPrompts: 5,
    pastAlternativePaths: 5,
    lifeChapterEvidence: 8,
  },
  TOTAL_JSON_CHARS: 12_000,
} as const;

export type ContextLimitKey = keyof typeof CONTEXT_LIMITS.TEXT;
