-- Add AI-generated forecast summary to check-ins.
-- One sentence describing what the check-in reveals about how the situation
-- is evolving. Generated by a lightweight Claude call after forecast
-- regeneration; nullable so existing rows and failures are handled gracefully.

alter table public.check_ins
  add column if not exists forecast_summary text;
